- name: installing jenkins
  hosts: localhost
  tasks:
    
    - name: download jenkins archive
      shell: sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

    - name: import key
      shell: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: install java
      shell: sudo yum upgrade

    - name: install jenkins
      shell: sudo yum install jenkins java-11-openjdk-devel

    - name: reload
      shell: sudo systemctl daemon-reload
