- name: installing jenkins
  hosts: localhost
  tasks:
    
    - name: download jenkins archive
      shell: sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

    - name: import key
      shell: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: install java
      shell: "yum upgrade -y"

    - name: install java
      shell: "yum install java-11 -y"
   
    - name: install jenkins
      shell: "yum install jenkins -y" 

    - name: reload
      shell: sudo systemctl daemon-reload
